# Generated by Django 5.1.6 on 2025-02-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marvelmodel',
            name='release_movie',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
