# Generated by Django 5.1.6 on 2025-04-05 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('SUITS', 'Suits'), ('SHIRTS', 'Shirts'), ('WEDDING SHERWANI', 'Wedding Sherwani')], max_length=20)),
                ('small_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('selling_price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('percentage', models.IntegerField(default=0)),
                ('price_and_quantity_total', models.IntegerField(default=0)),
                ('mens_image', models.ImageField(upload_to='mens_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='pet',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.customerdetail'),
        ),
        migrations.AddField(
            model_name='order',
            name='mens',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.mens'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mens'),
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
